---
title: "Figures"
author: "Yanelli Nunez"
date: "4/21/2021"
output:
 html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

This code you can run because it doesn't use patient data. Here I used the effect estimates I save from the models to make a figure for the effect estimates of average exposures and the distributed lags

```{r include=FALSE}

rm(list=ls())

# 1a Declare root directory
project.folder <- paste0(print(here::here()),'/')

# add folder locations
source(paste0(project.folder,'0_00_create_folder_structure.R'))

# add file locations
source(paste0(file.locations.folder,'file_locations.R'))

# load packages
 source(paste0(packages.folder,'packages.R'))

# load data
 source(paste0(code.folder, 'models/m_00_load_datasets.R'))


```

## 2. Estimate lags 1-10 and sample 100 cases/controls

```{r}

# arrange order of lags
lags <- data_lags %>%
  dplyr::mutate(lags = as.vector(lags)) %>%
group_by(nr, lobnr) %>%
  arrange(lags, .by_group = TRUE) 



  
# sample 500 cases/controls  
random_sample <- lags %>%
 group_by(nr, lobnr) %>%
  summarise() %>%
  ungroup() %>%
  sample_n(., 500)
  
  
# select sample from dataframe

sample_full <- inner_join(random_sample, lags, by = c("nr", "lobnr"))

```

## 3. Estimate lag autocorrelation

```{r}

autocor <- lags %>% 
  dplyr::select(nr, lobnr, mean_pm2.5) %>%
          group_by(nr, lobnr) %>%
          nest() %>% 
          mutate(cor = purrr::map(data, ~acf(., lag.max=10, type="correlation", plot=F))) %>%
          mutate(cor_estim = map(cor, ~as.data.frame(.x$acf))) %>%
  dplyr::select(-data, -cor) %>%
          unnest(cor_estim) %>%
  group_by(nr, lobnr) %>%
  mutate(lag = 0:10) %>%
 dplyr::rename(cor = V1) %>% 
  ungroup()


```

## 4. Viz of median

```{r}

# media 
median_autocor <- autocor %>%
  group_by(lag) %>%
  summarize(median_cor = median(cor)) 

# viz
median_fig <- median_autocor %>%
  ggplot(aes(x = lag, y = median_cor)) +
    # Add horizontal line a y=0
    geom_hline(yintercept = 0) +
    # Plot autocorrelations
    geom_point(size = 2) +
    geom_segment(aes(xend = lag, yend = 0), size = 1) +
  ylab("Autocorrelation (Median)") +
  xlab("Lag") +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 1)) +
  scale_y_continuous(limits = c(-0.3, 1), breaks = seq(-0.25, 1, by = 0.25)) +
  theme_minimal() +
  theme(
      #  axis.ticks.y=element_blank(),
        axis.text.x = element_text(size = 20),
       # axis.title.x = element_text(vjust = -0.1),
        axis.text.y = element_text(size = 20),
        axis.title = element_text(size = 20),
        #legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        strip.text = element_text(size = 20))


   
ggplotly(median_fig, tooltip = c("median_cor"))

```
